[theme]
primaryColor = "#1f77b4"
backgroundColor = "#ffffff"
secondaryBackgroundColor = "#f0f2f6"
textColor = "#262730"
font = "sans serif"

[server]
port = 8501
enableCORS = true
enableXsrfProtection = false
headless = true

[browser]
gatherUsageStats = false
# Force rebuild at Sun Oct 19 21:33:30 EDT 2025
